### ISSUE TITLE
vim-tux is outldated

### ISSUE THREAD

**Issue by chantisnake** [Link-Satonaka/chocopkgs#5]
vim has upgraded to 8.0

**Comment by Link-Satonaka** [comment]
Thanks for letting me know. My server which automatically updates my chocolatey packages is currently offline, and I won't be able to fix it until friday. The vim package points to the same URL no matter what, you can just `cinst -fy vim-tux` to get the latest release.

**Comment by chantisnake** [comment]
i think choco has a size verification system. since the new one has a different size, choco will not let you install the new ones.

You can try that.

**Comment by Link-Satonaka** [comment]
I have used this trick on many different packages. Did you try it before posting that it might not work?

**Comment by chantisnake** [comment]
hum, I have tried it again. it seems like it is work this time.

I will close this issue.
